In [2]:
#Q1
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print("Original temperatures:", temperature)

corrected_temperature = temperature + 2
print("Corrected temperatures (+2°C):", corrected_temperature)

fahrenheit = (temperature * 9 / 5) + 32
print("Temperatures in Fahrenheit:", fahrenheit)

above_32 = temperature[temperature > 32]
print("Readings greater than 32°C:", above_32)

count_above_32 = np.sum(temperature > 32)
print("Count of readings exceeding 32°C:", count_above_32)


Original temperatures: [25 28 31 35 38 27 33 40]
Corrected temperatures (+2°C): [27 30 33 37 40 29 35 42]
Temperatures in Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
Readings greater than 32°C: [35 38 33 40]
Count of readings exceeding 32°C: 4


In [3]:
#Q2
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
print("Steps matrix:\n", steps)

total_steps = np.sum(steps)
print("Total steps recorded:", total_steps)

mean_steps = np.mean(steps)
print("Mean number of steps:", mean_steps)

max_steps = np.max(steps)
min_steps = np.min(steps)
print("Maximum steps:", max_steps)
print("Minimum steps:", min_steps)

total_per_day = np.sum(steps, axis=0)
print("Total steps per day:", total_per_day)

total_per_user = np.sum(steps, axis=1)
print("Total steps per user:", total_per_user)

max_position = np.unravel_index(np.argmax(steps), steps.shape)
user_index, day_index = int(max_position[0]), int(max_position[1])
print("Position (user, day) with maximum steps:", (user_index, day_index))


Steps matrix:
 [[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]
Total steps recorded: 84200
Mean number of steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps per day: [26500 27300 30400]
Total steps per user: [18300 24500 14400 27000]
Position (user, day) with maximum steps: (3, 2)


In [4]:
#Q3
import numpy as np

original = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", original)

subset = original[1:5]
print("Subset:", subset)

subset[0] = 999
print("Original after modifying subset:", original)
print("Subset after modification:", subset)

subset_copy = original[1:5].copy()
subset_copy[0] = 500
print("Original after modifying copied slice:", original)
print("Copied slice after modification:", subset_copy)

matrix = np.arange(1, 13).reshape(3, 4)
print("3x4 matrix:\n", matrix)

first_row = matrix[0, :]
last_row = matrix[-1, :]
second_column = matrix[:, 1]
sub_matrix = matrix[1:3, 2:4]

print("First row:", first_row)
print("Last row:", last_row)
print("Second column:", second_column)
print("Rows 1-2, columns 2-3:\n", sub_matrix)

flattened = matrix.flatten()
raveled = matrix.ravel()
print("Flattened array:", flattened)
print("Raveled array:", raveled)

raveled[0] = 1000
print("Matrix after modifying raveled array:\n", matrix)
print("Raveled array is a view, original changed:", matrix.flatten()[0] == 1000)

flattened[0] = 2000
print("Matrix after modifying flattened array:\n", matrix)
print("Flattened array is a copy, original unchanged:", matrix[0, 0] != 2000)

print("Shape:", matrix.shape)
print("Number of dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Dtype:", matrix.dtype)


Original array: [1 2 3 4 5 6]
Subset: [2 3 4 5]
Original after modifying subset: [  1 999   3   4   5   6]
Subset after modification: [999   3   4   5]
Original after modifying copied slice: [  1 999   3   4   5   6]
Copied slice after modification: [500   3   4   5]
3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2, columns 2-3:
 [[ 7  8]
 [11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matrix after modifying raveled array:
 [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Raveled array is a view, original changed: True
Matrix after modifying flattened array:
 [[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Flattened array is a copy, original unchanged: True
Shape: (3, 4)
Number of dimensions: 2
Size: 12
Dtype: int64


In [5]:
#Q4
import numpy as np

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])

print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

X_T = X.T
print("Transpose of X:\n", X_T)

XtX = X.T @ X
print("X.T @ X:\n", XtX)

XtX_inv = np.linalg.inv(XtX)
print("Inverse of X.T @ X:\n", XtX_inv)

beta = XtX_inv @ X.T @ y
print("OLS coefficients (beta):", beta)

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("Predicted assistance score for new user:", predicted_score)


Shape of X: (4, 3)
Dimensions of X: 2
Transpose of X:
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse of X.T @ X:
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
OLS coefficients (beta): [-0.15921454  0.14083853 10.06302242]
Predicted assistance score for new user: 75.27862544779117
